[package]
name = "zr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
name = "zr"

[dependencies]
extendr-api = "0.8"
zarrs = { version = "0.23", features = ["ndarray", "filesystem", "async", "gzip", "blosc", "zstd", "sharding"] }
zarrs_object_store = "0.6"
object_store = { version = "0.13", features = ["http", "aws"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
serde_json = "1"
