# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_zr_wrappers", use_symbols = TRUE, package_name = "zr")

#' @usage NULL
#' @useDynLib zr, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Return
#' @export
apic <- function() .Call(wrap__apic)

#' Return
#' @export
raex <- function() .Call(wrap__raex)


# nolint end
