# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_zr_wrappers", use_symbols = TRUE, package_name = "zr")

#' @usage NULL
#' @useDynLib zr, .registration = TRUE
NULL

#' @export
zr_create_array_inner <- function(store, path, shape, chunks, dtype, fill_value, dimension_names, attributes_json) .Call(wrap__zr_create_array_inner, store, path, shape, chunks, dtype, fill_value, dimension_names, attributes_json)

#' @export
zr_write_subset_inner <- function(store, arr, start, shape, data_f64, data_i32) .Call(wrap__zr_write_subset_inner, store, arr, start, shape, data_f64, data_i32)

#' @export
zr_write_chunk_inner <- function(store, arr, chunk_index, data_f64, data_i32) .Call(wrap__zr_write_chunk_inner, store, arr, chunk_index, data_f64, data_i32)

#' @export
zr_erase_chunk_inner <- function(store, arr, chunk_index) .Call(wrap__zr_erase_chunk_inner, store, arr, chunk_index)

#' @export
zr_nodes_inner <- function(store, path) .Call(wrap__zr_nodes_inner, store, path)

#' @export
zr_zarrs_version <- function() .Call(wrap__zr_zarrs_version)

ZrStore <- new.env(parent = emptyenv())

ZrStore$new <- function(path) .Call(wrap__ZrStore__new, path)

ZrStore$new_http <- function(url) .Call(wrap__ZrStore__new_http, url)

ZrStore$new_s3 <- function(url) .Call(wrap__ZrStore__new_s3, url)

ZrStore$path <- function() .Call(wrap__ZrStore__path, self)

ZrStore$is_writable <- function() .Call(wrap__ZrStore__is_writable, self)

ZrStore$is_listable <- function() .Call(wrap__ZrStore__is_listable, self)

#' @export
`$.ZrStore` <- function (self, name) { func <- ZrStore[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ZrStore` <- `$.ZrStore`

ZrGroup <- new.env(parent = emptyenv())

ZrGroup$open <- function(store, path) .Call(wrap__ZrGroup__open, store, path)

ZrGroup$create <- function(store, path) .Call(wrap__ZrGroup__create, store, path)

ZrGroup$attributes_json <- function() .Call(wrap__ZrGroup__attributes_json, self)

ZrGroup$group_path <- function() .Call(wrap__ZrGroup__group_path, self)

#' @export
`$.ZrGroup` <- function (self, name) { func <- ZrGroup[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ZrGroup` <- `$.ZrGroup`

ZrArray <- new.env(parent = emptyenv())

ZrArray$open <- function(store, path) .Call(wrap__ZrArray__open, store, path)

ZrArray$shape <- function() .Call(wrap__ZrArray__shape, self)

ZrArray$chunk_shape <- function() .Call(wrap__ZrArray__chunk_shape, self)

ZrArray$dtype <- function() .Call(wrap__ZrArray__dtype, self)

ZrArray$fill_value_json <- function() .Call(wrap__ZrArray__fill_value_json, self)

ZrArray$dimension_names <- function() .Call(wrap__ZrArray__dimension_names, self)

ZrArray$attributes_json <- function() .Call(wrap__ZrArray__attributes_json, self)

ZrArray$metadata_json <- function() .Call(wrap__ZrArray__metadata_json, self)

ZrArray$ndim <- function() .Call(wrap__ZrArray__ndim, self)

ZrArray$array_path <- function() .Call(wrap__ZrArray__array_path, self)

ZrArray$read_subset_robj <- function(start, shape) .Call(wrap__ZrArray__read_subset_robj, self, start, shape)

ZrArray$read_all_robj <- function() .Call(wrap__ZrArray__read_all_robj, self)

ZrArray$read_chunk_robj <- function(chunk_index) .Call(wrap__ZrArray__read_chunk_robj, self, chunk_index)

#' @export
`$.ZrArray` <- function (self, name) { func <- ZrArray[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ZrArray` <- `$.ZrArray`


# nolint end
